import { Button } from "std-widgets.slint";
import "../resources/NotoSansSC-Regular.ttf";

export component AppWindow inherits Window {
    in-out property <string> time: "<time>";
    in-out property <string> ntp-server: "ntp.aliyun.com";
    in-out property <bool> check-button-enabled: true;
    in-out property <bool> check-succeed: false;
    in-out property <string> check-result: "";
    callback check-ntp-server();

    default-font-family: "Noto Sans SC";

    min-width: 380px;
    min-height: 180px;
    title: "ntp-checker";
    icon: @image-url("../resources/logo.png");
    background: #fafafa;

    VerticalLayout {
        padding: 12px;
        alignment: start;
        spacing: 8px;
        HorizontalLayout {
            alignment: start;
            Text {
                font-size: 15px;
                text: "local time: \{root.time}";
            }
        }

        HorizontalLayout {
            alignment: start;
            Text {
                y: 0px;
                padding-top: 4px;
                font-size: 15px;
                text: "ntp server address: ";
            }

            Rectangle {
                width: 150px;
                height: 24px;
                border-color: gray;
                border-width: 1px;
                TextInput {
                    x: 2px;
                    vertical-alignment: center;
                    font-size: 15px;
                    text: root.ntp-server;
                    edited => {
                        root.ntp-server = self.text;
                    }
                }
            }

            Text {
                font-size: 14px;
                text: " ";
            }
        }

        HorizontalLayout {
            alignment: start;
            Button {
                text: "check";
                // height: 28px;
                // width: 100px;
                // padding-top: -8px;
                primary: true;
                enabled: root.check-button-enabled;
                clicked => {
                    root.check-ntp-server();
                }
            }
        }

        HorizontalLayout {
            alignment: start;
            Text {
                color: root.check-succeed ? blue : red;
                text: "\{root.check-result}";
                font-size: 14px;
                font-family: "Noto Sans SC";
                wrap: word-wrap;
            }
        }
    }
}
